version: '2'
services: 
  searchbrew:
    image: searchbrew:0.1.0-SNAPSHOT
    ports:
      - "9000:9000"
  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    links:
      - cadvisor
      - searchbrew
    depends_on:
      - cadvisor